sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - pip install --upgrade pip --quiet

install:
  - pip install -r requirements.txt
  - pip install flask-optimize

before_script:
  - pyclean --verbose .

script:
  - python flask_optimize/__init__.py
  - python tests/flask_app.py

notifications:
  email: false